const rolesModel = require("../models/roles.model");

const createRoleQuery = async (details) => {
    try {
        const { roleName, roleCode, contents = [], createdBy } = details;

        // Basic validation
        if (!roleName) {
            return {
                status: false,
                statusCode: 400,
                message: "roleName is required",
            };
        }

        // Check if role already exists (by name or code)
        const existingRole = await rolesModel.findOne({
            $or: [
                { roleName: roleName.trim() },
                roleCode ? { roleCode: roleCode.trim().toLowerCase() } : null,
            ].filter(Boolean),
        });

        if (existingRole) {
            return {
                status: false,
                statusCode: 409,
                message: "Role already exists",
            };
        }

        // Create role
        const role = await rolesModel.create({
            roleName: roleName.trim(),
            roleCode: roleCode
                ? roleCode.trim().toLowerCase()
                : undefined, // auto-generated by schema if missing
            contents,
            createdBy
        });

        return {
            status: true,
            statusCode: 201,
            message: "New role created successfully",
            data: role,
        };
    } catch (error) {
        console.error("Create Role Error:", error);

        return {
            status: false,
            statusCode: 500,
            message: "Something went wrong",
        };
    }
};

const getRoleQuery = async () => {
    try {
        const roles = await rolesModel.find().populate({
            path: "createdBy",
            select: "email", // only fetch email
        });

        return {
            status: true,
            statusCode: 200,
            roles
        }
    } catch (error) {
        return {
            status: false,
            statusCode: 500,
            message: "Something went wrong",
        };
    }
}


const updateRoleQuery = async (details) => {
    try {
        const { roleName, roleCode, contents, roleId } = details;

        // 1️⃣ Find role
        const role = await rolesModel.findById(roleId);

        if (!role) {
            return {
                status: false,
                statusCode: 404,
                message: "Role not found",
            };
        }

        // 2️⃣ Check duplicate roleName
        if (roleName && roleName.trim() !== role.roleName) {
            const existingName = await rolesModel.findOne({
                roleName: roleName.trim(),
                _id: { $ne: roleId },
            });

            if (existingName) {
                return {
                    status: false,
                    statusCode: 409,
                    message: "Role name already exists",
                };
            }

            role.roleName = roleName.trim();

            // Auto-regenerate roleCode if not explicitly provided
            if (!roleCode) {
                role.roleCode = roleName
                    .toLowerCase()
                    .replace(/[^a-z0-9]/g, "");
            }
        }

        // 3️⃣ Check duplicate roleCode
        if (roleCode && roleCode.trim().toLowerCase() !== role.roleCode) {
            const existingCode = await rolesModel.findOne({
                roleCode: roleCode.trim().toLowerCase(),
                _id: { $ne: roleId },
            });

            if (existingCode) {
                return {
                    status: false,
                    statusCode: 409,
                    message: "Role code already exists",
                };
            }

            role.roleCode = roleCode.trim().toLowerCase();
        }

        // 4️⃣ Update contents
        if (Array.isArray(contents)) {
            role.contents = contents;
        }

        await role.save();

        return {
            status: true,
            statusCode: 200,
            message: "Role updated successfully",
            data: role,
        };
    } catch (error) {
        console.error("Update Role Error:", error);

        return {
            status: false,
            statusCode: 500,
            message: "Something went wrong",
        };
    }
};


const deleteRolesQuery = async (ids) => {
    try {

        console.log({ ids })
        ids = JSON.parse(ids)

        if (!ids || !Array.isArray(ids) || ids.length == 0) {
            return {
                status: false,
                statusCode: 400,
                message: "Provide an array of roles id"
            }
        }

        const inValidIds = ids.filter(id => !id.match(/^[0-9a-fA-F]{24}$/))

        if (inValidIds.length > 0) {
            return {
                status: false,
                statusCode: 400,
                message: "Invalid mongoDB ObjectId(s)",
                inValidIds
            }
        }

        const result = await rolesModel.deleteMany({ _id: { $in: ids } })

        return {
            status: true,
            statusCode: 200,
            message: `${result.deletedCount} role(s) delete successfully`,
            deletedCount: result.deletedCount
        }

    } catch (error) {
        return {
            status: false,
            statusCode: 500,
            message: error.message
        }
    }
}

module.exports = {
    createRoleQuery,
    getRoleQuery,
    updateRoleQuery,
    deleteRolesQuery
};
